GET http://127.0.0.1:8000/products/ HTTP/1.1
###
POST  http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "Television",
    "description": "This is a new product.",
    "price": 300,
    "stock": 14
}