GET http://127.0.0.1:8000/products/ HTTP/1.1

###
GET http://127.0.0.1:8000/products/1/ HTTP/1.1

###
DELETE http://127.0.0.1:8000/products/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyMDEzMDM5LCJpYXQiOjE3NjIwMTI3MzksImp0aSI6Ijk5ZmY4NzJmOGIxNDQ5M2FiNzgyMGNjZDEwNWZkNGJjIiwidXNlcl9pZCI6IjEifQ.GKMmiSyD0J5Uk_IuQSSZWRwf4wMu3aDAIsADrrHNEhA

###
PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyMDEzMDM5LCJpYXQiOjE3NjIwMTI3MzksImp0aSI6Ijk5ZmY4NzJmOGIxNDQ5M2FiNzgyMGNjZDEwNWZkNGJjIiwidXNlcl9pZCI6IjEifQ.GKMmiSyD0J5Uk_IuQSSZWRwf4wMu3aDAIsADrrHNEhA

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"    
}

###
POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxOTQ1Mjk4LCJpYXQiOjE3NjE5NDQ5OTgsImp0aSI6IjVmMjZjNmRjMTNmZDQxZmE5NDgyMGUxMzdmMDc3Y2I5IiwidXNlcl9pZCI6IjEifQ.Ax_dwL96qrMA5IB3_c4NavTpFIWNDpjPBCEJoe7-hXU

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"    
}
###
POST  http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}
###
GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxOTQ0NTY2LCJpYXQiOjE3NjE5NDQyNjYsImp0aSI6IjE3NGZhNTY4Y2E3YzQ1Y2Y4MjE3ZTdjMjlmM2U5YjAxIiwidXNlcl9pZCI6IjIifQ.psp0ZVMZd5sCvaF9-00fvMpLFrhFzJohurO8dbWZTfE
###
POST  http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MjAzMDMzMCwiaWF0IjoxNzYxOTQzOTMwLCJqdGkiOiJhZWY2ZWY3YTNkNWY0NWQ4YTk5YTJkYjgyMjUyNjVmOCIsInVzZXJfaWQiOiIxIn0.87Nfo1AmFtKf7Z1xXgQucGiF5tyMMWvcwatL07GgXqg"
}